name: LightningVision
version: 1.0
author: Mvye
main: com.mvye.lightningvision.LightningVision
api-version: 1.18
commands:
  lightningVision:
    description: Summon lighnting anywhere you look!
    usage: /<command>
    aliases: [toggleLV, menace]